name: Image scan
on:
  workflow_dispatch:
    inputs:
      image-name:
        description: "Image to csan"
        required: true
        default: "ghcr.io/it-at-m/pentaho-carte:latest"
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ inputs.image-name }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
